var canvas = document.getElementById('canvas');
var ctx = canvas.getContext('2d');
var snakeSize = 10;
var w = 400;
var h = 400;
var snake;
var food;
var score = 0;
var tail;
var btn = document.getElementById('button');
